---
name: gradle-build-pipeline
description: "Checkout, build and tag gradle projects"
inputs:
  docker_registry:
    description: "The registry to persist Docker images"
    required: true
  gpr_user:
    description: "Name of a user with read access to packages, required to get dependencies"
    required: true
  gpr_key:
    description: "Personal Access Token of the gpr_user with read access to packages, required to get dependencies"
    required: true
  helm_registry:
    description: "The registry to persist Helm charts"
    required: true
  skip_test:
    description: "Skip test execution (true|false)"
    required: false
    default: "false"
  token:
    description: "The workflow's GitHub token"
    required: true
outputs:
  chart_name:
    description: "The name of the helm chart, if published"
    value: ${{ steps.build.outputs.chart_name }}
  chart_version:
    description: "The version of the helm chart, if published"
    value: ${{ steps.build.outputs.chart_version }}
  module_name:
    description: "The name of the module"
    value: ${{ steps.read-module-info.outputs.name }}
runs:
  using: "composite"
  steps:
    - id: read-tools-choice
      name: "Read tools version"
      shell: bash
      run: |
        [ "${{ runner.debug }}" == 1 ] && set -xv
        set -u

        property_name=helm.client.download.version
        if grep -qs -w ^${property_name} gradle.properties; then
          helm_version="$(grep -w ^${property_name} gradle.properties | cut -d= -f2)"
        fi

        property_name=toolchainVersion
        if grep -qs -w ^${property_name} gradle/gradle-daemon-jvm.properties; then
          java_version="$(grep -w ^${property_name} gradle/gradle-daemon-jvm.properties | cut -d= -f2)"
        else
          java_version=21
        fi

        property_name=toolchainVendor
        if grep -qs -w ^${property_name} gradle/gradle-daemon-jvm.properties; then
          java_vendor="$(grep -w ^${property_name} gradle/gradle-daemon-jvm.properties | cut -d= -f2)"
        else
          java_vendor=corretto
        fi

        {
        [ -v helm_version ] && echo "helm_version=${helm_version}"
        echo "java_version=${java_version}"
        echo "java_vendor=${java_vendor}"
        } >>"${GITHUB_OUTPUT}"
    - name: "Configure git client"
      shell: bash
      run: |
        [ "${{ runner.debug }}" == 1 ] && set -xv
        set -u
        
        git config user.name "${{ github.actor }}"
        git config user.email "${{ github.actor }}@users.noreply.github.com"
    - id: qualify-build
      name: "Qualify build type"
      shell: bash
      run: |
        [ "${{ runner.debug }}" == 1 ] && set -xv
        set -u

        mode=feature_branch
        if [ "${{ github.ref }}" == "refs/heads/main" ] \
            || [[ "${{ github.ref }}" =~ ^refs/heads/main_[0-9]+$ ]]; then
          mode=push_to_release_branch
        fi

        if [ "${{ github.event_name }}" == "pull_request" ] \
            && (
              [ "${{ github.event.pull_request.base.ref }}" == "main" ] \
              || [[ "${{ github.event.pull_request.base.ref }}" =~ ^main_[0-9]+$ ]]
            ); then
          mode=pull_request_to_release_branch
        fi
        echo "::notice::mode is ${mode}"
        echo "mode=${mode}" >>"${GITHUB_OUTPUT}"
    - uses: actions/setup-java@v5
      with:
        distribution: ${{ steps.read-tools-choice.outputs.java_vendor }}
        java-version: ${{ steps.read-tools-choice.outputs.java_version }}
    - uses: gradle/actions/setup-gradle@v5
    - id: read-module-info
      name: "Read module information"
      shell: bash
      run: |
        [ "${{ runner.debug }}" == 1 ] && set -xv
        set -u

        name="$(./gradlew -q properties | grep ^name: | cut -d: -f 2 | tr -d ' ')"
        echo "::notice::name is ${name}"
        echo "name=${name}" >>"${GITHUB_OUTPUT}"
    - uses: azure/setup-helm@v4
      if: ${{ steps.read-tools-choice.outputs.helm_version }}
      with:
        version: ${{ steps.read-tools-choice.outputs.helm_version }}
    - id: define-version-validation
      name: "Is a release or a feature version needed?"
      shell: bash
      run: |
        [ "${{ runner.debug }}" == 1 ] && set -xv
        set -u
        
        case "${{ steps.qualify-build.outputs.mode }}" in
          feature_branch)
            mode=feature
            ;;
          push_to_release_branch | pull_request_to_release_branch)
            mode=release
            ;;
          *)
            echo "::error::Unknown mode ${{ steps.qualify-build.outputs.mode }}"
            exit 1
            ;;
        esac
        echo "::notice::mode is ${mode}"
        echo "mode=${mode}" >>"${GITHUB_OUTPUT}"
    - id: clq-extract
      name: "Extract tag from the changelog"
      uses: denisa/clq-action@v1
      with:
        changeMap: .github/clq/changemap.json
        mode: ${{ steps.define-version-validation.outputs.mode }}
    - id: define-build
      name: "Is this a test or publish build"
      shell: bash
      run: |
        [ "${{ runner.debug }}" == 1 ] && set -xv
        set -u

        function is_feature_branch_version() {
          # major.minor.patch-user-issue
          # user and issue relaxed to be any alpha-numeric sequence 
          if [[ "${{ steps.clq-extract.outputs.version }}" =~ ^[0-9]+(\.[0-9]+){2}(-[[:alnum:]]+){2}(-.+)?$ ]]; then
            return 0
          fi
          return 1
        }

        function is_publishable_feature_branch() {
          if ( [ "${{ github.event_name }}" == "push" ] && is_feature_branch_version ); then
            return 0
          fi
          return 1
        }

        if [ "${{ steps.qualify-build.outputs.mode }}" == "push_to_release_branch" ]; then
          kind=publish
          version="${{ steps.clq-extract.outputs.version }}"
        elif is_publishable_feature_branch; then
          kind=publish
          version="${{ steps.clq-extract.outputs.version }}-${{ github.run_id }}.${{ github.run_number }}.${{ github.run_attempt }}"
        else
          kind=test
        fi
        echo "::notice::kind is ${kind}"
        echo "kind=${kind}" >>"${GITHUB_OUTPUT}"
        echo "::notice::version is ${version:-undefined}"
        if [ -v version ]; then echo "version=${version}" >>"${GITHUB_OUTPUT}"; fi
    - name: "Tag source"
      shell: bash
      run: |
        [ "${{ runner.debug }}" == 1 ] && set -xv
        set -u
        
        readonly tag="${{ steps.clq-extract.outputs.tag }}"
        if [ "${{ steps.qualify-build.outputs.mode }}" == "push_to_release_branch" ]; then
          if [ "${{ steps.define-build.outputs.kind }}" == "publish" ]; then
            echo "::notice::Tagging ${tag}"
            readonly workflow_run="${{ github.run_id }}.${{ github.run_number }}.${{ github.run_attempt }}"
            git tag -m "Released by ${{ github.job }}, ${workflow_run}" -a "${tag}"
            git push origin "${tag}"
          fi
        elif [ "${{ steps.define-version-validation.outputs.mode}}" == "release" ]; then
          echo "::notice::Looking for existing ${tag}"
          if git ls-remote --exit-code --tags origin "refs/tags/${tag}" >/dev/null 2>&1; then
            echo "::error::tag $tag exists already"
            exit 1
          fi
        fi
    - id: build
      uses: Arda-cards/gradle-build-action@v3
      env:
        TOKEN: ${{ inputs.token }}
        USERNAME: ${{ github.actor }}
      with:
        gpr_user: ${{ inputs.gpr_user }}
        gpr_key: ${{ inputs.gpr_key }}
        docker_registry: ${{ inputs.docker_registry }}
        helm_registry: ${{ inputs.helm_registry }}
        kind: ${{ steps.define-build.outputs.kind }}
        skip_test: ${{ inputs.skip_test }}
        version: ${{ steps.define-build.outputs.version }}
    - uses: ncipollo/release-action@v1
      if: steps.qualify-build.outputs.mode == 'push_to_release_branch'
      with:
        tag: ${{ steps.clq-extract.outputs.tag }}
        prerelease: ${{ steps.clq-extract.outputs.status == 'prereleased' }}
        name: ${{ steps.clq-extract.outputs.name }}
        body: ${{ steps.clq-extract.outputs.changes }}
    - name: "Remove tag of failed build"
      if: failure() && steps.build.outcome == 'failure'
      shell: bash
      run: |
        [ "${{ runner.debug }}" == 1 ] && set -xv
        set -u
        
        if [ "${{ steps.define-build.outputs.kind }}" == "publish" ] \
            && [ "${{ steps.qualify-build.outputs.mode }}" == "push_to_release_branch" ] ; then
          readonly tag="${{ steps.clq-extract.outputs.tag }}"
          echo "::notice::Removing tag ${tag}"
          git push --delete origin "${tag}"
        fi
    - name: Store reports
      if: failure() && steps.build.outcome == 'failure'
      uses: actions/upload-artifact@v5
      with:
        name: reports
        if-no-files-found: ignore
        overwrite: true
        path: |
          **/build/reports/
          **/build/test-results/
