---
name: gradle-build-pipeline
description: "Checkout, build and tag gradle projects"
inputs:
  docker_registry:
    description: "The registry to persist Docker images"
    required: true
  gpr_user:
    description: "Name of a user with read access to packages, required to get dependencies"
    required: true
  gpr_key:
    description: "Personal Access Token of the gpr_user with read access to packages, required to get dependencies"
    required: true
  helm_registry:
    description: "The registry to persist Helm charts"
    required: true
  skip_test:
    description: "Skip test execution (true|false)"
    required: false
    default: "false"
  token:
    description: "The workflow's GitHub token"
    required: true
outputs:
  chart_name:
    description: "The name of the helm chart, if published"
    value: ${{ steps.build.outputs.chart_name }}
  chart_version:
    description: "The version of the helm chart, if published"
    value: ${{ steps.build.outputs.chart_version }}
  module_name:
    description: "The name of the module"
    value: ${{ steps.read-module-info.outputs.name }}
runs:
  using: "composite"
  steps:
    - name: "Configure git client"
      shell: bash
      run: |
        [ "${{ runner.debug }}" == 1 ] && set -xv
        set -u
        
        git config user.name "${{ github.actor }}"
        git config user.email "${{ github.actor }}@users.noreply.github.com"
    - id: read-tools-choice
      name: "Read tools version"
      shell: bash
      run: |
        [ "${{ runner.debug }}" == 1 ] && set -xv
        set -u

        property_name=helm.client.download.version
        if grep -qs -w ^${property_name} gradle.properties; then
          helm_version="$(grep -w ^${property_name} gradle.properties | cut -d= -f2)"
        fi

        property_name=toolchainVersion
        if grep -qs -w ^${property_name} gradle/gradle-daemon-jvm.properties; then
          java_version="$(grep -w ^${property_name} gradle/gradle-daemon-jvm.properties | cut -d= -f2)"
        else
          java_version=21
        fi

        property_name=toolchainVendor
        if grep -qs -w ^${property_name} gradle/gradle-daemon-jvm.properties; then
          java_vendor="$(grep -w ^${property_name} gradle/gradle-daemon-jvm.properties | cut -d= -f2)"
        else
          java_vendor=corretto
        fi

        {
        [ -v helm_version ] && echo "helm_version=${helm_version}"
        echo "java_version=${java_version}"
        echo "java_vendor=${java_vendor}"
        } >>"${GITHUB_OUTPUT}"
    - uses: actions/setup-java@v5
      with:
        distribution: ${{ steps.read-tools-choice.outputs.java_vendor }}
        java-version: ${{ steps.read-tools-choice.outputs.java_version }}
    - uses: gradle/actions/setup-gradle@v6
    - uses: azure/setup-helm@v5
      if: ${{ steps.read-tools-choice.outputs.helm_version }}
      with:
        version: ${{ steps.read-tools-choice.outputs.helm_version }}
    - id: read-module-info
      name: "Read module information"
      shell: bash
      run: |
        [ "${{ runner.debug }}" == 1 ] && set -xv
        set -u

        name="$(./gradlew -q properties | grep ^name: | cut -d: -f 2 | tr -d ' ')"
        echo "::notice::name is ${name}"
        echo "name=${name}" >>"${GITHUB_OUTPUT}"
    - uses: Arda-cards/qualify-build-action@dna/PDEV-957
      id: qualify-build
    - name: "Tag source"
      shell: bash
      run: |
        [ "${{ runner.debug }}" == 1 ] && set -xv
        set -u
  
        readonly tag="${{ steps.qualify-build.outputs.tag }}"
        if [ "${{ steps.qualify-build.outputs.target }}" == "push_to_release_branch" ]; then
          if [ "${{ steps.qualify-build.outputs.kind }}" == "publish" ]; then
            echo "::notice::Tagging ${tag}"
            readonly workflow_run="${{ github.run_id }}.${{ github.run_number }}.${{ github.run_attempt }}"
            git tag -m "Released by ${{ github.job }}, ${workflow_run}" -a "${tag}"
            git push origin "${tag}"
          fi
        elif [ "${{ steps.qualify-build.outputs.target}}" == "release" ]; then
          echo "::notice::Looking for existing ${tag}"
          if git ls-remote --exit-code --tags origin "refs/tags/${tag}" >/dev/null 2>&1; then
            echo "::error::tag $tag exists already"
            exit 1
          fi
        fi
    - id: build
      name: "Build, test and publish"
      shell: bash
      run: ${{ github.action_path }}/gradle-build.sh
      env:
        DOCKER_REGISTRY: ${{ inputs.docker_registry }}
        GPR_USER: ${{ inputs.gpr_user }}
        GPR_KEY:  ${{ inputs.gpr_key }}
        HELM_REGISTRY: ${{ inputs.helm_registry }}
        KIND: ${{ steps.qualify-build.outputs.kind }}
        SKIP_TEST: ${{ inputs.skip_test }}
        TOKEN: ${{ inputs.token }}
        VERSION: ${{ steps.qualify-build.outputs.version }}
    - id: clq-extract
      if: steps.qualify-build.outputs.trigger == 'push_to_release_branch'
      name: "Extract tag from the changelog"
      uses: denisa/clq-action@v1
      with:
        changeMap: .github/clq/changemap.json
        mode: ${{ steps.qualify-build.outputs.target }}
    - uses: ncipollo/release-action@v1
      if: steps.qualify-build.outputs.trigger == 'push_to_release_branch'
      with:
        tag: ${{ steps.qualify-build.outputs.tag }}
        prerelease: ${{ steps.clq-extract.outputs.status == 'prereleased' }}
        name: ${{ steps.clq-extract.outputs.name }}
        body: ${{ steps.clq-extract.outputs.changes }}
    - name: "Remove tag of failed build"
      if: failure() && steps.build.outcome == 'failure'
      shell: bash
      run: |
        [ "${{ runner.debug }}" == 1 ] && set -xv
        set -u
  
        if [ "${{ steps.qualify-build.outputs.kind }}" == "publish" ] \
            && [ "${{ steps.qualify-build.outputs.trigger }}" == "push_to_release_branch" ] ; then
          readonly tag="${{ steps.qualify-build.outputs.tag }}"
          echo "::notice::Removing tag ${tag}"
          git push --delete origin "${tag}"
        fi
    - name: Store reports
      if: failure() && steps.build.outcome == 'failure'
      uses: actions/upload-artifact@v7
      with:
        name: reports
        if-no-files-found: ignore
        overwrite: true
        path: |
          **/build/reports/
          **/build/test-results/
